---
- name: This is playbook to create user
  hosts: all
  connection: community.aws.aws_ssm  # Specify SSM connection type
  become: true
  gather_facts: False
  tasks:
  - name: Creating user john
    user: 
      name: john

  - name: Install httpd
    dnf:
      name: httpd
      state: installed 
   
  - name: start apache
    service:
      name: httpd
      state: started

  - name: Clone GitHub repository into /var/www/html
    ansible.builtin.git:
      repo: 'https://github.com/alirezatayebinejad/ecommerce-website-html-css.git'  # Replace with your repo URL
      dest: /var/www/html
      version: master  # Specify branch if needed
      force: yes
      update: yes      
 
  - name: Restart service httpd, in all cases
    ansible.builtin.service:
      name: httpd
      state: restarted     