---
# Ansible Galaxy Requirements File
#
# Installation Methods:
#
# 1. Install as a collection (recommended):
#    ansible-galaxy collection install -r requirements.yml
#
# 2. Install from Git directly:
#    ansible-galaxy collection install git+https://github.com/pratikargade/ansible-work.git
#
# 3. Install individual roles:
#    ansible-galaxy install -r requirements.yml
#
# 4. Use in your playbook with:
#    - name: pratikargade.ansible_work.users
#    - name: pratikargade.ansible_work.2fa_auth

collections:
  # This collection
  - name: pratikargade.ansible_work
    source: https://github.com/pratikargade/ansible-work.git
    type: git
    version: main
  
  # Add other collection dependencies here if needed
  # - name: community.general
  #   version: ">=1.0.0"
  # - name: ansible.posix
  #   version: ">=1.0.0"

roles:
  # Add role dependencies here if needed
  # - name: geerlingguy.docker
  #   version: ">=3.0.0"

