---
- name: Test AWS SSM Connection
  hosts: all
  gather_facts: no
  # connection: community.aws.aws_ssm   
  # connection: community.aws.aws_ssm
  vars: 
    ansible_connection: community.aws.aws_ssm 
    ansible_aws_ssm_bucket_name: devoptech-dev-terraform-backend
    ansible_aws_ssm_region: ap-south-1

  become: yes
  tasks:
    - name: Test connectivity
      command: uptime
      register: result

    - name: Print uptime
      debug:
        msg: "{{ result.stdout }}"
