plugin: aws_ec2
regions:
  - ap-south-1  # Your region
keyed_groups:
  - key: tags.Name
    prefix: 'tag_Name_'
hostnames:
  - tag:Name  # Use the Name tag for the hostname
compose:
  ansible_host: public_ip_address
filters:
  tag:Project: Texa  # Filter by a specific tag, e.g., Environment=production
