# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "devoptech-dev-terraform-backend"
    key            = "ssm_role/terraform.tfstate"
    region         = "ap-south-1"
    encrypt        = true
  }
}
