---
- name: When condition example
  hosts: all
  vars: 
    ansible_connection: community.aws.aws_ssm 
    ansible_aws_ssm_bucket_name: devoptech-dev-terraform-backend
    ansible_aws_ssm_region: ap-south-1
    user: 'john'
  become: true
  gather_facts: true
  tasks:
  - name: Creating user {{ user }}
    user: 
      name: "{{ user }}"
    when: ansible_os_family == "RedHat"   

  - name: Install packages
    dnf: 
      name: ['git','tree']
      state: installed
 