name: Run Ansible Playbook
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - master

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Ansible and required packages
      run: |
        python -m pip install --upgrade pip
        pip install ansible boto3 botocore awscli

    - name: Install Ansible Collections
      run: |
        ansible-galaxy collection install community.aws

    - name: AWS SSM plugin
      shell: bash
      run: |
        curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
        sudo dpkg -i session-manager-plugin.deb
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::637423592422:role/git-action-deploy-role
        aws-region: ap-south-1 

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory/aws_ec2.yaml simple-pay.yaml
